GAsk/GAsk/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Metadata;
using System.Threading.Tasks;
using FengCode.Libs.Utils.Text;
using GAsk.Library.BBL;
using GAsk.Library.Entity;
using GAsk.Library.Extensions;
using GAsk.Library.Services;
using GAsk.Library.Utils;
using GAsk.Models;
using GAsk.ViewComponents;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GAsk.Controllers
{
    /// <summary>
    /// 评论控制器
    /// </summary>
    [Authorize]
    public class CommentController : Controller
    {

        private readonly CommentService commentService;
        private readonly PersonService personService;
        private readonly HtmlService htmlService;
        private readonly PostService postService;

        public CommentController(CommentService commentService, PersonService personService, HtmlService htmlService, PostService postService)
        {
            this.commentService = commentService ?? throw new ArgumentNullException(nameof(commentService));
            this.personService = personService ?? throw new ArgumentNullException(nameof(personService));
            this.htmlService = htmlService ?? throw new ArgumentNullException(nameof(htmlService));
            this.postService = postService ?? throw new ArgumentNullException(nameof(postService));
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromBody] CommentEditModel model)
        {
            CommentView comment = await this.commentService.InsertAsync(model, this.User.GetUserId().Value);
            PersonView person = await this.personService.GetCurrentPersonViewAsync();
            return ViewComponent(typeof(CommentItemViewComponent), new { pLoginPerson = person, pCommentView = comment });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                await this.commentService.DeleteAsync(id, this.User.GetUserId().Value);
                return Json(AjaxResult.CreateDefaultSuccess());
            }
            catch (Exception ex)
            {
                return Json(AjaxResult.CreateByMessage(ex.Message, false));
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            Guid? loginUserId = this.User.GetUserId();
            Comment comment = await this.commentService.GetByIdAsync(id);
            if (comment == null || comment.IsDelete)
            {
                return NotFound();
            }
            else if (loginUserId==null || loginUserId.Value!=comment.PersonId)
            {
                return this.Forbid();
            }
            else
            {

                CommentEditModel model = new CommentEditModel
                {
                    Id = comment.Id,
                    Content = comment.HtmlContent,
                    ParentId = comment.ParentId,
                    PostId = comment.PostId,
                    PostType = (await this.postService.GetPostTypeAsync(comment.PostId)).Value
                };
                return View(model);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CommentEditModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (model.Id == null)
                    {
                        throw new Exception("评论ID不能为空");
                    }
                    Guid? loginUserId = this.User.GetUserId();
                    Comment comment = await this.commentService.GetByIdAsync(model.Id.Value);
                    if (comment == null || comment.IsDelete)
                    {
                        throw new Exception("该评论不存在，或已被删除");
                    }
                    else if (loginUserId == null || loginUserId.Value != comment.PersonId)
                    {
                        throw new Exception("没有该操作的权限");
                    }
                    else if (string.IsNullOrWhiteSpace(model.Content))
                    {
                        throw new Exception("内容不能为空");
                    }
                    else
                    {
                        string htmlContent = this.htmlService.ClearHtml(model.Content);
                        string textContent = this.htmlService.HtmlToText(htmlContent);
                        if (string.IsNullOrWhiteSpace(htmlContent))
                        {
                            throw new Exception("内容不能为空");
                        }
                        else
                        {
                            await this.commentService.ModifyAsync(comment.Id, htmlContent, textContent);
                            return Json(AjaxResult.CreateDefaultSuccess());
                        }
                    }
                }
                catch (ModelException ex)
                {
                    return this.Json(ex.ToAjaxResult());
                }
                catch (Exception ex)
                {
                    return this.Json(AjaxResult.CreateByMessage(ex.Message, false));
                }
            }
            else
            {
                return this.Json(ModelState.ToAjaxResult());
            }
        } 
    }
}

GAsk/GAsk/Views/Comment/Edit.cshtml
@model GAsk.Models.CommentEditModel

@{
    ViewData["Title"] = "修改评论";
}

@{
    string returnUrl = "";
    if (Model.PostType == GAsk.Library.Enums.PostType.Article)
    {
        returnUrl = Url.Action("Details", "Article", new { id = Model.PostId });
    }
    else if (Model.PostType == GAsk.Library.Enums.PostType.Question)
    {
        returnUrl = Url.Action("Details", "Question", new { id = Model.PostId });
    }
    returnUrl = returnUrl + "#" + Model.Id;
}

<div class="container">
    <div class="row">
        <div class="col">
            <nav class="bg-white">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">首 页</a></li>
                    <li class="breadcrumb-item active" aria-current="page">修改评论</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form action="/" method="post" id="form">
                <div class="card">
                    <div class="card-header bg-light-blue">
                        修改评论
                    </div>
                    <div class="card-body">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="Id" />
                        <input type="hidden" asp-for="PostId" />
                        <input type="hidden" asp-for="ParentId" />
                        <textarea asp-for="Content"></textarea>
                    </div>
                    <div class="card-footer">
                        <button class="btn btn-primary mr-2" id="btn-save">保 存</button>
                        <a href="@returnUrl" class="btn btn-secondary">返  回</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section js{
    <partial name="_ValidationScriptsPartial" />
    <script src="~/assets/tinymce/tinymce.min.js"></script>

    <script>
        $(function () {
            DomHelper.setTinymce("#Content", 300);
            $("#btn-save").click(function () {
                tinyMCE.triggerSave();
                $("#btn-save").attr("disabled", "true");
                $("#btn-save").html(`<span class="spinner-border spinner-border-sm" role="status"></span> 正在提交...`);
                let form = document.getElementById("form");
                AjaxHelper.postForm('@Url.Action("Edit","Comment")', form).done(function (result) {
                    if (result.Success) {
                        window.location.href = "@returnUrl";
                    } else {
                        AjaxHelper.showFormError(form, result);
                    }
                }).fail(function () {
                    DialogHelper.showErrorDialog("提交失败");
                }).always(function () {
                    $("#btn-save").removeAttr("disabled");
                    $("#btn-save").text("保 存");
                })
            })
        })
    </script>
}