GAsk/GAsk/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FengCode.Libs.Utils.Paging;
using GAsk.Areas.Admin.Models;
using GAsk.Library.BBL;
using GAsk.Library.Entity;
using GAsk.Library.Enums;
using GAsk.Library.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GAsk.Areas.Admin.Controllers
{
    /// <summary>
    /// 用户管理控制器
    /// </summary>
    [Authorize(Roles = "SuperAdmin,Admin")]
    public class UserController : BaseController
    {
        private readonly PersonService personService;

        public UserController(PersonService personService)
        {
            this.personService = personService ?? throw new ArgumentNullException(nameof(personService));
        }

        [HttpGet]
        public async Task<IActionResult> Manage(int page = 1, string search = "", RoleFilterType roleFilter = RoleFilterType.All)
        {
            PagingResult<PersonView> result = await this.personService.SearchAsync(search, page, roleFilter, Library.Enums.SearchType.ALL);
            UserManageModel model = new UserManageModel(result, search, roleFilter);
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> RoleModify(Guid id)
        {
            PersonView loginUser = await this.personService.GetCurrentPersonViewAsync();
            PersonView DoUser = await this.personService.GetPersonViewAsync(id);
            // 管理员不能修改其他管理员或站点管理员
            if (loginUser.RoleType == RoleType.Admin && (DoUser.RoleType== RoleType.Admin || DoUser.RoleType == RoleType.SuperAdmin))
            {
                return this.View("Forbid");
            }
            else
            {
                return View(new UserRoleModifyModel { DoUser = DoUser, LoginUser = loginUser, Id = DoUser.Id, Role = DoUser.RoleType });
            }
        }

        [HttpPost]
        public async Task<IActionResult> RoleModify(Guid id,RoleType role)
        {
            try
            {
                PersonView loginUser = await this.personService.GetCurrentPersonViewAsync();
                PersonView DoUser = await this.personService.GetPersonViewAsync(id);
                if (DoUser == null)
                {
                    throw new Exception("该用户不存在");
                }
                else if (DoUser.RoleType == RoleType.SuperAdmin)
                {
                    throw new Exception("无权修改网站管理员");
                }
                else if (role == RoleType.SuperAdmin)
                {
                    throw new Exception("无权设置为网站管理员");
                }
                else if (loginUser.RoleType != RoleType.Admin && loginUser.RoleType != RoleType.SuperAdmin)
                {
                    throw new Exception("仅管理员拥有操作权限");
                }
                else if (loginUser.RoleType == RoleType.Admin && (role == RoleType.Admin || role==RoleType.SuperAdmin))
                {
                    throw new Exception("该操作无权限");
                }
                else
                {
                    await this.personService.ModifyRoleAsync(DoUser.Id, role);
                    return this.Json(AjaxResult.CreateDefaultSuccess());
                }
            }
            catch (Exception ex)
            {
                return this.Json(AjaxResult.CreateByMessage(ex.Message, false));
            }
        }

        /// <summary>
        /// 删除用户
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> Remove(Guid id)
        {
            try
            {
                await this.personService.RemoveAsync(id);
                return this.Json(AjaxResult.CreateDefaultSuccess());
            }
            catch (Exception ex)
            {
                return this.Json(AjaxResult.CreateByMessage(ex.Message, false));
            }
        }

        /// <summary>
        /// 恢复被删除的用户
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> RestoreRemove(Guid id)
        {
            try
            {
                await this.personService.RestoreRemoveAsync(id);
                return this.Json(AjaxResult.CreateDefaultSuccess());
            }
            catch (Exception ex)
            {
                return this.Json(AjaxResult.CreateByMessage(ex.Message, false));
            }
        }

        /// <summary>
        /// 禁言用户
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> Mute(Guid id)
        {
            try
            {
                await this.personService.MuteByIdAsync(id);
                return this.Json(AjaxResult.CreateDefaultSuccess());
            }
            catch (Exception ex)
            {
                return this.Json(AjaxResult.CreateByMessage(ex.Message, false));
            }
        }

        /// <summary>
        /// 恢复被禁言的用户
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> RestoreMute(Guid id)
        {
            try
            {
                await this.personService.RestoreMuteByIdAsync(id);
                return this.Json(AjaxResult.CreateDefaultSuccess());
            }
            catch (Exception ex)
            {
                return this.Json(AjaxResult.CreateByMessage(ex.Message, false));
            }
        }
    }
}

GAsk/GAsk/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FengCode.Libs.Mapper;
using FengCode.Libs.Utils.Paging;
using GAsk.Library.BBL;
using GAsk.Library.Entity;
using GAsk.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GAsk.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly PersonService personService;
        private readonly ActivityService activityService;
        private readonly PostService postService;
        private readonly FavoriteService favoriteService;

        public UserController(PersonService personService, ActivityService activityService, PostService postService, FavoriteService favoriteService)
        {
            this.personService = personService;
            this.activityService = activityService;
            this.postService = postService;
            this.favoriteService = favoriteService;
        }

        /// <summary>
        /// 个人主页
        /// </summary>
        [AllowAnonymous]
        public async Task<IActionResult> Page(Guid id, int page = 1)
        {
            if (page < 1)
            {
                return NotFound();
            }
            PersonView person = await this.personService.GetPersonViewAsync(id);
            if (person == null || person.IsDelete)
            {
                return NotFound();
            }
            else
            {
                Person p = ObjectMapper.Map<PersonView, Person>(person);
                PagingResult<ActivityView> pagingResult = await this.activityService.GetPagingResultsAsync(p, page);
                UserPageViewModel model = new UserPageViewModel(person, pagingResult);
                return View(model);
            }
        }

        /// <summary>
        /// 个人文章
        /// </summary>
        /// <param name="id">用户ID（不是文章ID）</param>
        public async Task<IActionResult> Article(Guid id,int page = 1)
        {
            if (page < 1)
            {
                return NotFound();
            }
            PersonView person = await this.personService.GetPersonViewAsync(id);
            if (person == null || person.IsDelete)
            {
                return NotFound();
            }
            else
            {
                Person p = ObjectMapper.Map<PersonView, Person>(person);
                PagingResult<PostView> pagingResult = await this.postService.GetPagingResultAsync(person, Library.Enums.PostResultType.Article, page);
                if (pagingResult.PageCount >1 && page > pagingResult.PageCount)
                {
                    return NotFound();
                }
                UserArticleViewModel model = new UserArticleViewModel(pagingResult,person);
                return View(model);
            }
        }
        /// <summary>
        /// 个人提问
        /// </summary>
        public async Task<IActionResult> Question(Guid id,int page = 1)
        {
            if (page < 1)
            {
                return NotFound();
            }
            PersonView person = await this.personService.GetPersonViewAsync(id);
            if (person == null || person.IsDelete)
            {
                return NotFound();
            }
            else
            {
                Person p = ObjectMapper.Map<PersonView, Person>(person);
                PagingResult<PostView> pagingResult = await this.postService.GetPagingResultAsync(person, Library.Enums.PostResultType.Question, page);
                if (pagingResult.PageCount > 1 && page > pagingResult.PageCount)
                {
                    return NotFound();
                }
                UserQuestionViewModel model = new UserQuestionViewModel(pagingResult, person);
                return View(model);
            }
        }

        /// <summary>
        /// 个人收藏
        /// </summary>
        public async Task<IActionResult> Favorite(Guid id, int page = 1)
        {
            if (page < 1)
            {
                return NotFound();
            }
            PersonView person = await this.personService.GetPersonViewAsync(id);
            if (person == null || person.IsDelete)
            {
                return NotFound();
            }
            else
            {
                PagingResult<PostView> pagingResult = await this.favoriteService.GetFavoritePagingResultAsync(id, page);
                if (pagingResult.PageCount > 1 && page > pagingResult.PageCount)
                {
                    return NotFound();
                }
                UserFavoriteViewModel model = new UserFavoriteViewModel(pagingResult, person);
                return View(model);
            }
        }
    }
}

GAsk/GAsk/Areas/Admin/Views/User/Forbid.cshtml
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary text-white">
                <h5 class="modal-title" id="exampleModalLongTitle">提示</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="model">
                <p>不具备修改该用户的权限</p>
            </div>   
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">关 闭</button>
            </div>
        </div>
    </div>
</div>

GAsk/GAsk/Areas/Admin/Views/User/Index.cshtml
@{
    ViewData["Title"] = "用户管理";
}

<div class="bg-white d-flex align-items-center justify-content-between">
    <h5 class="mb-0 ml-2">用户管理</h5>
    <ol class="breadcrumb mb-0 bg-white align-self-end">
        <li class="breadcrumb-item">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index">首页</a>
        </li>
    </ol>
</div>


<div class="container-fluid" id="vue-app">
    <div class="row">
        <div class="col">
            <div class="card mt-2">
                <div class="card-body">
                    <form autocomplete="off" class="form-inline" id="form-search" v-on:submit.prevent="onSearch">
                        <div class="input-group mr-3">
                            <input type="text" name="search" id="search" class="form-control" value="" placeholder="输入用户的账号或昵称" />
                            <div class="input-group-append">
                                <button class="btn btn-outline-info" type="button" title="搜索" id="btn-search" v-bind:disabled="isSearch == true">
                                    <span v-if="isSearch" class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                                    <i v-else class="fa fa-search" aria-hidden="true"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="table-responsive mt-2">
                <table class="table table-hover table-bordered bg-white table-nowrap">
                    <thead>
                        <tr class="table-warning">
                            <th scope="col">登录账号</th>
                            <th scope="col">昵称</th>
                            <th scope="col">注册时间</th>
                            <th scope="col">操作</th>
                        </tr>
                    </thead>
                    <tbody id="tbody">
                        <tr v-if="isLoaded == false">
                            <td colspan="4">
                                <div class="p-2 text-md-center">正在加载数据...</div>
                            </td>
                        </tr>
                        <tr v-if="isLoaded == true && items.length == 0">
                            <td colspan="4">
                                <div class="p-2 text-md-center">暂无数据</div>
                            </td>
                        </tr>
                        <tr v-for="item in sortData">
                            <td v-text="item.Id"></td>
                            <td v-text="item.Name"></td>
                            <td v-if="item.IsHide">
                                <button class="btn btn-outline-warning btn-sm" v-on:click="changeStatus(item)">
                                    <i class="fa fa-eye-slash" aria-hidden="true"></i>
                                </button>
                            </td>
                            <td v-else>
                                <button class="btn btn-outline-success  btn-sm" v-on:click="changeStatus(item)">
                                    <i class="fa fa-eye" aria-hidden="true"></i>
                                </button>
                            </td>
                            <td v-text="item.OrderNum"></td>
                            <td>
                                <button class="btn btn-danger btn-sm mr-2" v-on:click="removeItem(item)">删 除</button>
                                <button class="btn btn-warning btn-sm mr-2" v-on:click="modifyItem(item)">修 改</button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
      $(function () {
             let data = {
                isLoaded: false,
                items:[]
            };
            let vm = new Vue({
                el: "#vue-app",
                data: data,
                methods: {
                    removeItem: function (item) {
                        DialogHelper.showConfirmDialog(`确认删除'${item.Name}'吗？`, function () {
                            AjaxHelper.postJson("@Url.Action("Delete")", item).done(function (postResult) {
                                if (postResult.Success) {
                                    data.items.splice(data.items.indexOf(item), 1);
                                    DialogHelper.showToastSuccess("删除成功");
                                } else {
                                    DialogHelper.showErrorDialog(postResult.Message);
                                }
                            })
                        })
                    },
                    modifyItem: function (item) {
                        let id = item.Id;
                        $.get("@Url.Action("Edit")/" + id).done(function (html) {
                            placeholder.html(html);
                            $("#modify_modal").modal("show");
                            $('#modify_modal').on('shown.bs.modal', function () {
                                $('#Name').focus();
                                $("#Name").select();
                            });
                            let formDom = document.getElementById("form");
                            $.validator.unobtrusive.parse(formDom);
                            // 处理表单提交
                            $(formDom).data("validator").settings.submitHandler = function () {
                                AjaxHelper.postForm('@Url.Action("Edit")', formDom).done(function (result) {
                                    if (result.Success) {
                                        item.Name = result.Context.Name;
                                        item.IsHide = result.Context.IsHide;
                                        item.OrderNum = result.Context.OrderNum;
                                        $("#modify_modal").modal("hide");
                                        DialogHelper.showToastSuccess("操作成功");
                                    } else {
                                        AjaxHelper.showFormError(formDom, result);
                                    }
                                    return false;
                                });
                                return false;
                            };
                        })
                    },
                    changeStatus: function (item) {
                        let msg = "";
                        if (item.IsHide) {
                            msg = `是否确认显示《${item.Name}》？`;
                        } else {
                            msg = `是否确认隐藏《${item.Name}》？`;
                        }
                        DialogHelper.showConfirmDialog(msg, function () {
                            let url = "@Url.Action("ChangeStatus")";
                            AjaxHelper.postJson(url, item).done(function (result) {
                                if (result.Success) {
                                    item.IsHide = !item.IsHide;
                                    DialogHelper.showToastSuccess("操作成功");
                                } else {
                                    DialogHelper.showErrorDialog(result.Message);
                                }
                            });
                        })
                    }
                },
                computed: {
                    sortData: function () {
                        return data.items.sort(sortObject);
                    }
                }
            });
            // 加载数据
            $.post("@Url.Action("GetAll")").done(function (result) {
                if (result.Success) {
                    data.isLoaded = true;
                    data.items = result.Context;
                } else {
                    DialogHelper.showErrorDialog(result.Message);
                }
            });
            // 弹出新增对话框
            let placeholder = $("#placeholder");
            $("#btn-add").click(function () {
                $.get("@Url.Action("Create")").done(function (html) {
                        placeholder.html(html);
                        $("#add_modal").modal("show");
                        $('#add_modal').on('shown.bs.modal', function () {
                            $('#Name').focus();
                        })
                        let formDom = document.getElementById("form");
                        $.validator.unobtrusive.parse(formDom);
                        // 处理表单提交
                        $(formDom).data("validator").settings.submitHandler = function () {
                            AjaxHelper.postForm('@Url.Action("Create")', formDom).done(function (result) {
                                if (result.Success) {
                                    data.items.push(result.Context);
                                    $("#add_modal").modal("hide");
                                    DialogHelper.showToastSuccess("操作成功");
                                } else {
                                    AjaxHelper.showFormError(formDom, result);
                                }
                                return false;
                            });
                            return false;
                        };
                })
            });
        })
</script>

GAsk/GAsk/Areas/Admin/Views/User/Manage.cshtml
@model UserManageModel
@{
    ViewData["Title"] = "用户管理";
}
<div class="bg-white d-flex align-items-center justify-content-between">
    <h5 class="mb-0 ml-2">用户管理</h5>
    <ol class="breadcrumb mb-0 bg-white align-self-end">
        <li class="breadcrumb-item">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index">首页</a>
        </li>
    </ol>
</div>

<div class="container-fluid" id="vue-app">
    <div class="row">
        <div class="col">
            <div class="card mt-2">
                <div class="card-body">
                    <div class="row">
                        <form autocomplete="off" class="form-inline" id="form-search">
                            <div class="col-auto">
                                <input type="text" asp-for="@Model.Search" class="form-control" value="" placeholder="输入登录账号或昵称" />
                            </div>
                            <div class="col-auto">
                                <select asp-for="@Model.RoleFilter" asp-items="@Model.SelectListItems" class="form-control"></select>
                            </div>
                            <div class="col-auto">
                                <button class="btn btn-outline-info" type="submit" title="搜索" id="btn-search">
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                    <span class="ml-2">搜 索</span>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="table-responsive mt-2">
                <table class="table table-hover table-bordered bg-white table-nowrap">
                    <thead>
                        <tr class="table-warning">
                            <th scope="col">头像</th>
                            <th scope="col">登录账号</th>
                            <th scope="col">昵称</th>
                            <th scope="col">注册时间</th>
                            <th scope="col">操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.PagingResult.Data.Count == 0)
                        {
                            <tr>
                                <td colspan="5">
                                    <span>暂无数据</span>
                                </td>
                            </tr>
                        }
                        else
                        {
                            @foreach (var item in Model.PagingResult.Data)
                            {
                                <tr id="@item.Id">
                                    <td>
                                        <img src="@item.Avatar" alt="头像" width="32" height="32" />
                                    </td>
                                    <td>@item.AccountName</td>
                                    <td>@item.NickName</td>
                                    <td>@item.CreateTime</td>
                                    <td>
                                        <a asp-controller="User" asp-action="Page" asp-route-id="@item.Id" asp-area="" target="_blank" class="btn btn-success btn-sm mr-2">个人主页</a>
                                        <button class="btn btn-primary btn-sm mr-2" onclick="modifyRole('@item.Id')">设置角色</button>
                                        @if (item.IsMute)
                                        {
                                            <button class="btn btn-outline-warning btn-sm mr-2 btn-mute" data-is-mute="@item.IsMute">恢复禁言</button>
                                        }
                                        else
                                        {
                                            <button class="btn btn-warning btn-sm mr-2 btn-mute" data-is-mute="@item.IsMute">禁言</button>
                                        }
                                        @if (item.IsDelete)
                                        {
                                            <button class="btn btn-outline-danger btn-sm mr-2 btn-delete" data-is-delete="@item.IsDelete">恢复删除</button>
                                        }
                                        else
                                        {
                                            <button class="btn btn-danger btn-sm mr-2 btn-delete" data-is-delete="@item.IsDelete">删除</button>
                                        }
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <vc:bootstrap-pager for-page-size="@Model.PagingResult.PageSize" for-row-count="@Model.PagingResult.RowCount"></vc:bootstrap-pager>
        </div>
    </div>
</div>

<div id="placeholder"></div>

<script>
    // 弹出新增对话框
  let placeholder = $("#placeholder");
    function modifyRole(userId) {
      let url = '@Url.Action("RoleModify","User")/?id=' + userId;
      $.get(url).done(function (html) {
        placeholder.html(html);
      });
    }
    $(document).on("click", ".btn-delete", function (event) {
      let parent = event.currentTarget.closest("tr");
      let id = $(parent).attr("id");
      let formData = new FormData();
      let self = $(this);
      formData.append("id", id);
      if (self.data("is-delete") == "False") {
        DialogHelper.showConfirmDialog("将要删除该用户，确认操作吗？", function () {
          self.attr("disabled", "disabled");
          AjaxHelper.postFormData('@Url.Action("Remove")',formData).done(function (result) {
            if (result.Success) {
                self.text("恢复删除");
              self.removeClass("btn-danger");
              self.addClass("btn-outline-danger");
              self.data("is-delete", "True");
              DialogHelper.showMessageDialog("操作成功");
            } else {
              DialogHelper.showErrorDialog(result.Message);
            }
          }).always(function () {
            self.removeAttr("disabled");
          })
        })
      } else {
        DialogHelper.showConfirmDialog("将要恢复该用户，确认操作吗?", function () {
          self.attr("disabled", "disabled");
          AjaxHelper.postFormData('@Url.Action("RestoreRemove")',formData).done(function (result) {
            if (result.Success) {
              self.text("删除");
              self.removeClass("btn-outline-danger");
              self.addClass("btn-danger");
              self.data("is-delete", "False");
              DialogHelper.showMessageDialog("操作成功");
            } else {
              DialogHelper.showErrorDialog(result.Message);
            }
          }).always(function () {
            self.removeAttr("disabled");
          })
        })
      }
    });


    $(document).on("click", ".btn-mute", function (event) {
      let parent = event.currentTarget.closest("tr");
      let id = $(parent).attr("id");
      let formData = new FormData();
      let self = $(this);
      formData.append("id", id);
        if (self.data("is-mute") == "False") {
        DialogHelper.showConfirmDialog("将要禁言该用户，确认操作吗？", function () {
          self.attr("disabled", "disabled");
          AjaxHelper.postFormData('@Url.Action("Mute")',formData).done(function (result) {
            if (result.Success) {
                self.text("恢复禁言");
                self.removeClass("btn-warning");
                self.addClass("btn-outline-warning");
                self.data("is-mute", "True");
              DialogHelper.showMessageDialog("操作成功");
            } else {
              DialogHelper.showErrorDialog(result.Message);
            }
          }).always(function () {
            self.removeAttr("disabled");
          })
        })
      } else {
        DialogHelper.showConfirmDialog("将要恢复该用户，确认操作吗?", function () {
          self.attr("disabled", "disabled");
          AjaxHelper.postFormData('@Url.Action("RestoreMute")',formData).done(function (result) {
              if (result.Success) {
                self.text("删除");
                self.removeClass("btn-outline-warning");
                self.addClass("btn-warning");
                self.data("is-mute", "False");
                DialogHelper.showMessageDialog("操作成功");
            } else {
              DialogHelper.showErrorDialog(result.Message);
            }
          }).always(function () {
            self.removeAttr("disabled");
          })
        })
      }
    });

</script>